### ISSUE TITLE
Is there a way to test this without a ui16?

### ISSUE THREAD

**Issue by ResourceHog** [NaturalDevCR/MyUiPro#5]
Any assistance would be greatly appreciated!

**Comment by NaturalDevCR** [comment]
It should work with any of the 3 models (Ui12, Ui16, Ui24r), and there is a way to test it (in a very limited way) with the demo available online... when you first setup the mixer IP, instead you can paste any of the Soundcraft Ui demo links available in the official Soundcraft website... 

This would put the app in Demo mode, but still, almost nothing is gonna work, since it will not be capable to connect to a real mixer... the only thing you could test is the multi screen freature.
